[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "minigit"
version = "0.1.0"
description = "A lightweight Git implementation in Python from scratch."
readme = "README.md"
authors = [{ name = "Rusdan Lamsa", email = "zxs1230017zazx@gmail.com" }]
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = []

[project.scripts]
minigit = "minigit.cli:main"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
